### ISSUE TITLE
home-manager rolling is terribly out of date

### ISSUE THREAD

**Issue by Lord-Valen** [DeterminateSystems/flakehub-mirror#20]
Looks like the action has been failing since December of last year.

**Comment by shackra** [comment]
no updates on this?

**Comment by grahamc** [comment]
Hey folks, sorry. We've been looking into this, and made a minor effort to fix this. The issue is the Home Manager flake has many thousands of outputs, and requires many gigabytes of memory to fully evaluate. Even on an extremely large runner, we run out of memory trying to evaluate it.

Maybe we could find a way to turn off the extreme volume of checks they have for this?

**Comment by grahamc** [comment]
We solved it! 🎉. Sorry it took forever.

**Comment by shackra** [comment]
@grahamc then https://flakehub.com/flake/nix-community/home-manager will update soon, right?

**Comment by grahamc** [comment]
The nixos-unstable variant updated already:

<img width="617" alt="image" src="https://github.com/DeterminateSystems/flakehub-mirror/assets/76716/06dd4912-47d1-466c-b9d7-7a6e6bb7075e">

which one are you looking for?

**Comment by shackra** [comment]
@grahamc had this in mind:

![image](https://github.com/DeterminateSystems/flakehub-mirror/assets/1055216/335ba69e-f17b-41c2-88f9-81bbedcd931c)

**Comment by grahamc** [comment]
Got it! 24.05 is now being mirrored. Thank you!
